[package]
name = "christian-filesystem-workers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.4.0"
libc = "0.2.147"
nix = "0.26.2"
rand = "0.8.5"
structopt = "0.3.26"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
